### ISSUE TITLE
startup.lsp not found but eval_exception gives line number 1 error 23

### ISSUE THREAD

**Issue by ryan11lb426** [jimspr/robosim#1]
I've included a picture, it looks like the resource file "startup.lsp" is missing I found the STARTUP.LSP file in the Samples directory tried tossing it into the robosim directory is. No dice so I attempted to rename it to "startup.lsp", but again luck wasn't on my side. I followed about as far as where ifstream ifs attempts to open the resource and the filebuffer keeps coming up null. (on a note isn't the Nocreate flag enabled on ifstreams by default?). I know the file says its hunting for STARTUP.LSP(1) but I did check and the string ifs is being fed is "startup.lsp"

I didn't poke around much more seeing as I'm what they call an idiot, I imagine it's something simple making it too challenging a task for me.

![robosimERROR](https://user-images.githubusercontent.com/11170199/182052354-0b8afba3-a5fc-4ea3-9533-df6bc43ef000.PNG)

**Comment by jimspr** [comment]
Sorry about that. What I am doing right now is setting the "Working Directory" under Debugging properties to be the samples directory:  $(SolutionDir)samples
![image](https://user-images.githubusercontent.com/15218002/182139994-d1feddc6-187a-458d-918e-042ede5f3fb4.png)
